services:
  - type: web
    name: mhc-backend
    env: python
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: ALLOWED_ORIGINS
        value: https://tu-frontend.netlify.app
